- name: Copy configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yml"
    dest: $HOME

- name: Apply configuration
  shell: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-deployment.yml"
  args:
    chdir: $HOME