---
- name: "Download kubectl"
  shell: curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.4/2023-08-16/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Apply execute permissions"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy binary to $PATH"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add path to shell"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME